config/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import LoginView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LoginView.as_view(), name="login"),
    path("dashboard/", include("dashboard.urls")),
    path("api/", include("dashboard.api")),
]

dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path('search/', views.SearchView.as_view(), name='search'),

    path("user/<int:pk>/", views.UserView.as_view(), name="user"),
    path("user/<int:livestream_id>/delete/", views.UserView.stop_stream, name="stop_stream"),
    path("change-visibility/<int:livestream_id>/", views.UserView.as_view(), name="change_visibility"),
    path("stream/", views.StreamView.as_view(), name="stream"),
    path("auth_stream/", views.auth_stream, name="auth_stream"),

    path("group/<int:pk>/", views.GroupView.as_view(), name="group_homepage"),
    path("group/<int:group_id>/invite", views.GroupView.invite_user, name="invite_user"),

    path("viewport/<int:user_id>/<int:viewport_id>/", views.ViewportView.as_view(), name="viewport"),
    path("viewport/post_viewport/", views.ViewportView.post, name="post_viewport"),
    path("viewport/<int:viewport_id>/delete/", views.ViewportView.delete, name="delete"),
]

dashboard/models.py
from django.contrib.gis.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, Group
from django.conf import settings

class MapChoice(models.Model):
    name = models.CharField(max_length=255)
    api_key = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
class Marker(models.Model):
    name = models.CharField(max_length=255)
    location = models.PointField()

    def __str__(self):
        return self.name
    
class Livestream(models.Model):
    title = models.CharField(max_length=255, default='')
    source = models.CharField(max_length=255, default='')
    type = models.CharField(max_length=255, default='', blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_livestreams')
    groups = models.ManyToManyField(Group, related_name='livestreams', blank=True) 
    latest_frame = models.ImageField(upload_to='frames', blank=True, null=True) 
    is_live = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
    def is_public(self):
        return self.groups.filter(name="Public").exists()
    
class Viewport(models.Model):
    name = models.CharField(max_length=255, default="Viewport")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='viewports')
    livestreams = models.ManyToManyField(Livestream, related_name='viewports')
    date_created = models.DateTimeField(auto_now_add=True)
    time_created = models.TimeField(auto_now_add=True)
    
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        """
        Creates and saves a User with the given email, username, and password.
        """
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')
        
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, username, password):
        """
        Creates and saves a superuser with the given email, username, and password.
        """
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=255, unique=False)
    email = models.EmailField(max_length=255, unique=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    groups = models.ManyToManyField(Group, related_name='group_memberships', blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'password']

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

dashboard/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.db.models import Q
from .models import CustomUser, Livestream

class InviteUserForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("User with this email does not exist.")
        return email

class LivestreamVisibilityForm(forms.ModelForm):
    form_name = forms.CharField(widget=forms.HiddenInput(), initial='visibility_form')
    livestream_id = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = Livestream
        fields = ('groups', 'livestream_id')

    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.none(), 
        widget=forms.CheckboxSelectMultiple,
        required=False)
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        # add all groups that the user is a member of and the Public/Private groups to queryset
        self.fields['groups'].queryset = Group.objects.filter(Q(id__in=user.groups.all()) | Q(name__in=['Public', 'Private']))

class SRTLinkForm(forms.Form):
    srt_link = forms.URLField(
        label='RTSP Link',
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'rtsp://your-url'})
    )

dashboard/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.http import JsonResponse, Http404, HttpResponseNotFound, HttpRequest
from json import JSONDecodeError

from django.views import generic, View
from django.views.generic.edit import FormView
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.csrf import csrf_exempt

from rest_framework import views, status
from rest_framework.parsers import JSONParser
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.decorators import api_view

from django.db.models import Q

from asgiref.sync import async_to_sync, sync_to_async

from config.celery import auth_login, auth_path, post_stream
from .models import Livestream, CustomUser
from .serializers import *
from .forms import *

import logging
logger = logging.getLogger(__name__)

class DashboardView(generic.ListView):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.all()
        context['users'] = CustomUser.objects.all()
        context['livestreams'] = Livestream.objects.all()
        context['is_authenticated'] = self.request.user.is_authenticated
        context['username'] = self.request.user.username if self.request.user.is_authenticated else ''
        context['viewports'] = self.request.user.viewports.all() if self.request.user.is_authenticated else ''
        return context
    
    def get_queryset(self):
        return Livestream.objects.all()

# TODO:
# - Use formview instead of generic view to handle post requests
class GroupView(generic.DetailView):
    model = Group
    template_name = "dashboard/group_homepage.html"

    @require_POST
    def invite_user(request, group_id):
        group = Group.objects.get(pk=group_id)

        if request.method == 'POST':
            form = InviteUserForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data.get('email')
                user = CustomUser.objects.get(email=email)
                group.members.add(user)
                group.save()
                messages.success(request, f'User {user} invited to {group.name}!')
                return redirect('dashboard:group_homepage', pk=group_id)
        else:
            form = InviteUserForm()

        return render(request, 'dashboard/invite_user.html', {'form': form, 'group': group})
    
class SearchView(View):

    @require_GET
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q', '')
        if query:
            search_results = Livestream.objects.filter(
                Q(title__icontains=query) |
                Q(created_by__username__icontains=query)
            )
            data = LivestreamSerializer(search_results, many=True).data
        else:
            data = LivestreamSerializer(Livestream.objects.all(), many=True).data
        return JsonResponse(data, safe=False)        
    
class StreamAPIView(LoginRequiredMixin, views.APIView):
    serializer_class = LivestreamSerializer
    
    @require_GET
    def get_serializer_context(self):
        return {
            'request': self.request,
            'format': self.format_kwarg,
            'view': self
            }
    
    @require_GET
    def get_serializer(self, *args, **kwargs):
        kwargs['context'] = self.get_serializer_context()
        return self.serializer_class(*args, **kwargs)
    
    @require_POST
    def post(self, request):
        try:
            data = JSONParser().parse(request)
            serializer = LivestreamSerializer(data=data)
            if serializer.is_valid(raise_exception=True):
                serializer.save()
                return Response(serializer.data)
            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except JSONDecodeError:
            return JsonResponse({"result": "error","message": "Json decoding error"}, status= 400)
        
class StreamView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
    template_name = "dashboard/stream.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_authenticated'] = self.request.user.is_authenticated
        context['username'] = self.request.user.username if self.request.user.is_authenticated else ''
        livestreams = Livestream.objects.all()
        context['livestreams'] = livestreams
        context['hls_links'] = {livestream.id: livestream.hls for livestream in livestreams if livestream.hls}
        return context
    
    def test_func(self):
        return self.request.user.groups.filter(name='Theia').exists()
    
    def handle_no_permission(self):
        raise Http404("You are not authorized to view this page")
    
class UserAPIView(LoginRequiredMixin, views.APIView):
    serializer_class = CustomUserSerializer

    @require_GET
    def get_serializer_context(self):
        return {
            'request': self.request,
            'format': self.format_kwarg,
            'view': self
            }
    
    @require_GET
    def get_serializer(self, *args, **kwargs):
        kwargs['context'] = self.get_serializer_context()
        return self.serializer_class(*args, **kwargs)
    
    @require_POST
    def post(self, request):
        try:
            data = JSONParser().parse(request)
            serializer = CustomUserSerializer(data=data)
            if serializer.is_valid(raise_exception=True):
                serializer.save()
                return Response(serializer.data)
            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except JSONDecodeError:
            return JsonResponse({"result": "error","message": "Json decoding error"}, status= 400)    
        
class UserView(LoginRequiredMixin, FormView):
    model = CustomUser
    template_name = "dashboard/user_homepage.html" 
    form_class = LivestreamVisibilityForm  # This is used only for the GET request.

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['visibility_form'] = LivestreamVisibilityForm(user=self.request.user)
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def post(self, request, *args, **kwargs):
        logger.info("POST request: ")
        logger.info(request.POST)
        form_name = request.POST.get('form_name')
        logger.info("form_name: ")
        logger.info(form_name)

        if form_name == 'visibility_form':
            form_class = LivestreamVisibilityForm
        else:
            return self.form_invalid(None)
        
        form = self.get_form(form_class)
        logger.info("post_data after form: ")
        logger.info(form)

        if form.is_valid():
            logger.info("form is valid")
            logger.info
            form.livestream_id = request.POST.get('livestream_id')
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
            
    def form_valid(self, form):
            livestream_id = form.cleaned_data.get('livestream_id')
            try:
                livestream = Livestream.objects.get(pk=livestream_id)
            except Livestream.DoesNotExist:
                return HttpResponseNotFound("Livestream not found")
            
            selected_groups = form.cleaned_data.get('groups')
            livestream.groups.set(selected_groups)
            livestream.save()

            return super().form_valid(form)
    
    def form_invalid(self, form):
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('dashboard:user', kwargs={'pk': self.request.user.id})

    #TODO: refactor this into the post method above and add a formview to make the request
    def stop_stream(request, livestream_id):
        try:
            livestream = Livestream.objects.get(pk=livestream_id)
            if livestream in request.user.created_livestreams.all():
                livestream.delete()
                return JsonResponse({"status": "success"}, status=200)
            else:
                return JsonResponse({"status": "error", "message": "Livestream not found in user's livestreams"}, status=404)
        except Livestream.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Livestream not found"}, status=404)

# TODO:
# - restructure viewportview into separate formviews to handle get, post, and delete requests
class ViewportView(generic.DetailView):
    model = Viewport
    template_name = "dashboard/viewport.html"
    
    # get the most recent viewport created by the user
    def get_object(self):
        user_id = self.kwargs['user_id']
        viewport_id = self.kwargs['viewport_id']
        return Viewport.objects.filter(user__id=user_id, id=viewport_id).latest('time_created')
    
    # return pk as the pk of the most recent viewport created by the user
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_id'] = self.kwargs['user_id']
        context['viewport_id'] = self.kwargs['viewport_id']
        return context
    
    @require_POST
    def post(request):

dashboard/templates/dashboard/agency_homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ agency.name }}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'dashboard/profile.css' %}">
    </head>
    <body>
        <header class="p-3 text-bg-dark">
            <div class="d-flex flex-row align-items-right justify-content-center justify-content-lg-start">
              <a href="/dashboard" role="button" class="btn btn-sm btn-outline-light">Home</a>
            </div>
        </header>
        <main class="form-signin w-100">
            <h1 class="my-3 fw-normal text-center">{{ agency.name }}</h1>
            <div class="pl-3 text-center">
                <h4>{{ agency.members.count }} {% if agency.members.count == 1 %}Member{% else %}Members{% endif %}</h2>
            </div>
        </main>
    </body>
</html>

dashboard/templates/dashboard/group_homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ group.name }}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'dashboard/profile.css' %}">
    </head>
    <body>
        <header class="p-3 text-bg-dark">
            <div class="d-flex flex-row align-items-right justify-content-center justify-content-lg-start">
              <a href="/dashboard" role="button" class="btn btn-sm btn-outline-light">Home</a>
            </div>
        </header>
        <main class="form-signin w-100">
            <h1 class="my-3 fw-normal text-center">{{ group.name }}</h1>
            <div class="pl-3 text-center">
                <h4>{{ group.members.count }} {% if group.members.count == 1 %}Member{% else %}Members{% endif %}</h2>
            </div>
        </main>
    </body>
</html>

dashboard/templates/dashboard/invite_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body class="text-center">
        <header class="p-3 text-bg-dark">
            <div class="d-flex flex-row align-items-right justify-content-center justify-content-lg-start">
              <a href="/dashboard" role="button" class="btn btn-sm btn-outline-light">Home</a>
            </div>
        </header>
        <main class="form-signin w-100 m-auto">
            {% block content %}
            <h2>Invite User to {{ agency.name }}</h2>
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit">Invite</button>
            </form>
          {% endblock %}
        </main>
    </body>
</html>

dashboard/templates/dashboard/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Login</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'dashboard/login.css' %}"> 
    </head>
    <body class="text-center">
        <header class="p-3 text-bg-dark">
            <div class="d-flex flex-row align-items-right justify-content-center justify-content-lg-start">
              <a href="/dashboard" role="button" class="btn btn-sm btn-outline-light">Home</a>
            </div>
        </header>
        <main class="form-signin w-100 m-auto">
            <h1 class="h3 mb-3 fw-normal">Please log in</h1>
            
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-floating">
                        <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" class="form-control" id="floatingInput">
                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                    </div>
                {% endfor %}
                <button class="w-100 btn btn-lg btn-primary" type="submit">log in</button>
            </form>
        </main>
    </body>
</html>

dashboard/templates/dashboard/stream.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ user.username }} | New Stream</title>
        <meta charset="utf-8">
        {% csrf_token %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'dashboard/profile.css' %}">
        <script src="{% static 'dashboard/jquery.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    </head>
    <body class="text-center">
        <header class="p-3 text-bg-dark">
            <div class="d-flex flex-row align-items-right justify-content-center justify-content-lg-start">
              <a href="/dashboard" role="button" class="btn btn-sm btn-outline-light">Home</a>
            </div>
        </header>
        <main class="container">
            {% for stream in livestreams %}
                {% if "rtsp" in stream.source %}
                    <p>{{ stream.get_title }}</p>
                    <video id="video-{{ stream.id }}" class="hls" controls></video>
                {% endif %}
            {% endfor %}
        </main>
    </body>
    <script>
        var hlsLinks = {{ hls_links|safe }};
    </script>
    <script src="{% static 'dashboard/stream.js' %}"></script>
</html>

dashboard/templates/dashboard/user_homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{{ user.username }} | Profile</title>
        <meta charset="utf-8">
        {% csrf_token %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="{% static 'dashboard/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'dashboard/bootstrap/bootstrap.bundle.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'dashboard/profile.css' %}">
    </head>
    <body class="text-center">
        <header class="p-3 text-bg-dark">
            <div class="d-flex flex-row align-items-right justify-content-center justify-content-lg-start">
              <a href="/dashboard" role="button" class="btn btn-sm btn-outline-light">Home</a>
            </div>
        </header>
        <main class="container">
            <section class="py-5 container">
                <h1 class="h3 mb-3 ">{{ user.username }}</h1>
            </section>
            <div class="container-fluid">

                <div class="container list-container">
                    <table class="table my-4 justify-content-between">
                        <thead>
                            <tr>
                                <th scope="col">Protocol</th>
                                <th scope="col">Your stream URL</th>
                            </tr>
                        </thead>
                        <tbody class="justify-content-between">

                                <tr class="">
                                    <td>
                                        RTSP
                                    </td>
                                    <td>
                                        rtsp://stream.kleinfourlabs.com:8554/{{ user.id }}/stream{{ user.created_livestreams.count }}
                                    </td>
                                </tr>
                                <tr class="">
                                    <td>
                                        RTMP
                                    </td>
                                    <td>
                                        rtmp://stream.kleinfourlabs.com:1935/{{ user.id }}/stream{{ user.created_livestreams.count }}
                                    </td>
                                </tr>

                        </tbody>
                    </table>
                </div>

                <div class="container list-container">
                    {% if user.viewports.count > 0 %}
                    <h1 class="h3 my-3">Viewports</h1>
                    <table class="table my-4 justify-content-between">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Created At</th>
                                <th scope="col">Stream Count</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="justify-content-between">
                            {% for viewport in user.viewports.all %}
                                <tr class="">
                                    <td>{{ viewport.name }}</td>
                                    <td>{{ viewport.date_created }}</td>
                                    <td>{{ viewport.livestreams.count }}</td>
                                    <td>
                                        <button class="delete-viewport-btn btn btn-sm btn-outline-danger" data-viewport-id="{{ viewport.id }}">Delete</button>
                                        <button class="open-viewport-btn btn btn-sm btn-outline-secondary" data-viewport-id="{{ viewport.id }}">View in New Tab</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p class="text-muted">You have not created any viewports yet.</p>
                    {% endif %}
                </div>

                <div class="container list-container">
                    {% if user.created_livestreams.count > 0 %}
                    <h1 class="h3 mb-3 ">Streams</h1>
                    <table class="table justify-content-between">
                        <thead>
                            <tr>
                                <th scope="col">Title</th>
                                <th scope="col">Visibility</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody class="justify-content-between">
                            {% for stream in user.created_livestreams.all %}
                                <tr>
                                    <td scope="row">{{ stream.title }}</td>
                                    <td>
                                        <div class="dropdown show">
                                            <a class="btn btn-sm btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle='dropdown' aria-haspopup="true" aria-expanded="false">
                                              {% for group in stream.groups.all %}
                                                {{ group.name }}
                                              {% endfor %}
                                            </a>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                                <form action="{% url 'dashboard:change_visibility' stream.id %}" method="post">
                                                    {% csrf_token %}
                                                    {{ visibility_form.form_name }}
                                                    <input type="hidden" name="livestream_id" value="{{ stream.id }}"/>

                                                    {% for group in visibility_form.groups.field.queryset %}
                                                        <div class="form-check">
                                                            {% if group in stream.groups.all %}
                                                                <input class="form-check-input" type="checkbox" value="{{ group.id }}" name="groups" id="group{{ forloop.counter }}" onchange="uncheckPrivatePublic(this);" checked>
                                                            {% elif group in user.groups.all %}
                                                                <input class="form-check-input" type="checkbox" value="{{ group.id}}" name="groups" id="group{{ forloop.counter }}" onchange="uncheckPrivatePublic(this);">
                                                            {% else %}
                                                                <input class="form-check-input nongroup" type="checkbox" value="{{ group.id}}" name="groups" id="group{{ forloop.counter }}" onchange="uncheckPrivatePublic(this);">
                                                            {% endif %}
                                                            <label class="form-check-label" for="group{{ forloop.counter }}">
                                                            {{ group.name }}
                                                            </label>
                                                        </div>
                                                    {% endfor %}
                                                    <button type="submit" class="btn btn-primary submit-btn" data-stream-id="{{ stream.id }}">Save</button>
                                                </form>
                                            </div>
                                          </div>
                                    </td>
                                    <td>
                                        <button class="stop-btn btn btn-sm btn-outline-danger" data-stream-id="{{ stream.id }}">Stop</button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </main>
        <script src="{% static 'dashboard/profile.js' %}"></script>
        <script>
            let id = "{{ user.id }}";
            setUserId(id);
          </script>
    </body>
</html>